name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, primary]
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Stop Docker
        run: |
          docker stop animal-therapy
          docker rm animal-therapy
        continue-on-error: true
      - name: Build Docker Image
        run: docker build -t animal-therapy .
      - name: Start Docker
        run: docker run -d -p 4000:4000 --name animal-therapy animal-therapy